---
- hosts: all
  vars_files:
    - users.yml
    - variables.yml
  roles:
    - { role: deploy-setup, tags: ['setup', 'deploy'] }
    - { role: system, tags: ['setup', 'system'] }
    - { role: common, tags: ['setup', 'common'] }
    - { role: docker, tags: ['setup', 'docker'] }
    - { role: plex, tags: ['plex'] }
