---
  - name: Update packages
    yum:
      name: "*"
      update_cache: yes
      state: latest

  - name: Install packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - epel-release
      - yum-utils

  - name: Purge old kernels on reboot
    cron:
      name: "Purge old kernels on reboot"
      special_time: reboot
      job: "package-cleanup --oldkernels --count=2"
      state: present

  - name: Disallow SSH password authentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
      state: present
    notify: Restart ssh

  - name: Disallow root SSH access
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
      state: present
    notify: Restart ssh
