---
  - set_fact:
      old_kernel: "{{ ansible_kernel | version_compare('4.12', '<') }}"

  - debug:
      msg: "Kernel up-to-date, nothing to do"
    when: not old_kernel

  - debug:
      msg: "Kernel too old, starting update..."
    when: old_kernel

  - name: Import ELRepo GPG Key
    rpm_key:
      key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
      state: present
    when: old_kernel

  - name: Add ELRepo
    yum:
      name: http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
      update_cache: yes
      state: present
    when: old_kernel

  - name: Install newest mainline stable Kernel
    yum:
      name: kernel-ml
      enablerepo: elrepo-kernel
      state: installed
    when: old_kernel

  - name: Set default boot to new Kernel
    lineinfile:
      dest: /etc/default/grub
      regexp: "^GRUB_DEFAULT="
      line: "GRUB_DEFAULT=0"
      state: present
    when: old_kernel

  - name: Recreate UEFI Kernel config
    shell: "grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg"
    when: old_kernel

  - name: Reboot system
    shell: sleep 5 && shutdown -r now "Ansible kernel updated"
    async: 1
    poll: 0
    when: old_kernel

  - name: Wait 60sec for server to come back
    wait_for_connection:
      timeout: 60
