---
    - name: Get sabnzbd uid
      shell: "id -u sabnzbd"
      register: uid

    - name: Get sabnzbd gid
      shell: "id -g sabnzbd"
      register: gid

    - name: Create common sabnzbd directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
        owner: sabnzbd
        group: sabnzbd
      with_items:
        - /opt/sabnzbd
        - "{{ data_mount }}/sabnzbd/incomplete-downloads"
        - "{{ data_mount }}/sabnzbd/nzb"

    - name: Create the sabnzbd dowlnoad directory
      file:
        path: "{{ item }}"
        state: directory
        mode: 0775
        owner: sabnzbd
        group: content
      with_items:
        - "{{ data_mount }}/sabnzbd/downloads"

    - name: Stop and remove existing container
      docker_container:
        name: sabnzbd
        state: absent

    - name: Create and start container
      docker_container:
        name: sabnzbd
        hostname: "{{ inventory_hostname }}"
        image: "linuxserver/sabnzbd:{{ sabnzbd.tag }}"
        pull: yes
        published_ports:
          - "8080:8080/tcp"
          - "9090:9090/tcp"
        env:
          HOSTNAME: "sabnzbd"
          PUID: "{{ uid.stdout }}"
          PGID: "{{ gid.stdout }}"
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/tmp:/tmp"
          - "/opt/sabnzbd:/config"
          - "{{ data_mount }}/sabnzbd/downloads:/downloads"
          - "{{ data_mount }}/sabnzbd/incomplete-downloads:/incomplete-downloads"
          - "{{ data_mount }}/sabnzbd/nzb:/nzb"
        restart_policy: always
        networks:
          - name: common
            aliases:
              - sabnzbd
        state: started
