---
  - name: Install common packages
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - bash-completion
      - htop
      - iotop
      - nethogs
      - tree
      - nano
      - mc
      - ncdu
      - unzip
      - p7zip
      - rsync
      - python-pip

  - name: Install pip modules
    pip:
      name: "{{ item }}"
    with_items:
      - docker-py

  - name: Create content directories
    file:
      path: "{{ item }}"
      state: directory
      mode: 0775
      owner: root
      group: content
    with_items:
      - "{{ data_mount }}/video/tv"
      - "{{ data_mount }}/video/movies"
