---
  - name: Get plex uid
    shell: "id -u plex"
    register: uid

  - name: Get plex gid
    shell: "id -g plex"
    register: gid

  - name: Create common Plex directories
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
      owner: plex
      group: plex
    with_items:
      - /home/plex/transcode
      - /opt/plex

  - name: Stop and remove existing container
    docker_container:
      name: plex
      state: absent

  - name: Check for existing preferences
    stat:
      path: "/opt/plex/Library/Application Support/Plex Media Server/Preferences.xml"
    register: plex_prefs

  - name: Ask for PlexPass claim token
    pause:
      prompt: "Enter PlexPass claim token from plex.tv/claim"
    register: plex_claim
    when: plex_prefs.stat.exists == False

  - name: Create and start container
    docker_container:
      name: plex
      hostname: "{{ inventory_hostname }}"
      image: "plexinc/pms-docker:{{ plex.tag }}"
      pull: yes
      published_ports:
        - "32400:32400/tcp"
        - "3005:3005/tcp"
        - "8324:8324/tcp"
        - "32469:32469/tcp"
        - "1900:1900/udp"
        - "32410:32410/udp"
        - "32412:32412/udp"
        - "32413:32413/udp"
        - "32414:32414/udp"
        - "33400:33400/tcp"
        - "33443:33443/tcp"
      env:
        HOSTNAME: "Plex"
        PLEX_UID: "{{ uid.stdout }}"
        PLEX_GID: "{{ gid.stdout }}"
        PLEX_CLAIM: "{{ plex_claim.user_input | default(omit) }}"
        ALLOWED_NETWORKS: "192.168.1.0/24"
      volumes:
        - "/home/plex/transcode:/transcode"
        - "/opt/plex:/config"
        - "/mnt:/mnt"
      restart_policy: always
      state: started
